cms/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django_distill import distill_path
from cms.models import Article
from . import views


def get_article_slugs_for_django_distill():
    for article in Article.objects.all():
        yield {'slug': article.slug}


def get_none_for_django_distill():
    return None

        
app_name='cms'
urlpatterns = [
    path('', views.index, name='index'),
    distill_path('', views.index, name='index', distill_func=get_none_for_django_distill, distill_file='index.html'),

    path("articles/<slug:slug>", views.article_detail, name="article_detail"),
    distill_path('articles/<slug:slug>', views.article_detail, name='article_detail', distill_func=get_article_slugs_for_django_distill, distill_file='articles/{slug}.html'),

    path('about/', views.about, name='about'),
    distill_path('about/', views.about, name='about', distill_func=get_none_for_django_distill, distill_file='about.html'),

    path('contact/', views.contact, name='contact'),
    distill_path('contact/', views.contact, name='contact', distill_func=get_none_for_django_distill, distill_file='contact.html'),

]

urlpatterns += staticfiles_urlpatterns()

django_static/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('cms.urls'))
]

if settings.DEBUG is False:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cms/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django_quill.fields import QuillField
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class Article(models.Model):
    title = models.TextField()
    content = QuillField()
    teaser = models.CharField(blank=True,null=True, max_length=1000)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    published = models.BooleanField(default=False)
    slug = models.SlugField(null=False, unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("cms:article_detail", kwargs={"slug": self.slug})
 


class Settings(models.Model):
    dest_dir = models.CharField(max_length=255, help_text="Default directory for exported articles.")
    site_name = models.CharField(max_length=255, default="", help_text="Site name")
    site_headline = models.CharField(max_length=255, default="", help_text="Site headline")
    site_teaser = models.CharField(max_length=255, default="", help_text="Site teaser")

    class Meta:
        verbose_name = 'Settings'
        verbose_name_plural = 'Settings'
    
    def clean(self):
        # Ensure only one instance exists
        if Settings.objects.exclude(pk=self.pk).exists():
            raise ValidationError("Only one instance of 'Settings' is allowed.")

    def save(self, *args, **kwargs):
        # Run clean method before saving
        self.clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Settings (dest_dir={self.dest_dir})"

cms/forms.py
from django import forms
from .models import Article

class QuillEditor(forms.Textarea):
    template_name = 'widgets/quill_editor.html'

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content', 'published']

        widgets = {
            'content': QuillEditor(),
        }

cms/views.py
import os
import subprocess

from django.shortcuts import get_object_or_404, render
from rest_framework import viewsets
from django.template.loader import render_to_string
from django.conf import settings

from .models import Article, Settings
from .serializers import ArticleSerializer
from .utils import get_dest_base_dir


# Create your views here.
def index(request):
    articles = Article.objects.filter(published=True).order_by('-created_at')
    context = {'articles': articles}
    return render(request, 'cms/index.html', context=context)


def about(request):
    articles = Article.objects.filter(published=True).order_by('-created_at')
    context = {'articles': articles}
    return render(request, 'cms/about.html', context=context)


def contact(request):
    articles = Article.objects.filter(published=True).order_by('-created_at')
    context = {'articles': articles}
    return render(request, 'cms/contact.html', context=context)


def article_detail(request, slug):
    print(f'looking for slug {slug}')
    article = Article.objects.get(slug=slug, published=True)
    context = {'article': article}
    return render(request, 'cms/post.html', context=context)


def export_to_static(id):
    # deploy command: python manage.py distill-local /private/var/www/nginx_static/django_static/test
    
    # Fetch the article from the database
    article = get_object_or_404(Article, id=id, published=True)
    serializer = ArticleSerializer(article)
    serializer_output_dict = serializer.data
    content = serializer_output_dict.get('content')

    # Use data from serializer
    context = {
        'title': serializer.data['title'],
        'content': content,
        'author': article.author.username,
        'created_at': serializer.data['created_at']
    }

    # Render the template with the article's context
    html_content = render_to_string('cms/static_article_template.html', context=context)

    # Get the directory from Settings or use default
    article_name = article.title.replace(' ', '_').lower()
    dest_dir = os.path.join(get_dest_base_dir(), article_name) # /article/destination/path/article_name/

    if not os.path.exists(dest_dir):
        os.makedirs(dest_dir)

    # copy html file
    html_file_name = article_name + '.html'
    html_dest_path = os.path.join(dest_dir, html_file_name) # /article/destination/path/article_name/article_name.html

    with open(html_dest_path, 'w') as f:
        f.write(html_content)

    # copy assets folder
    source_assets_path = os.path.join(settings.BASE_DIR, 'cms', 'templates', 'cms', 'assets/')
    destination_assets_path = os.path.join(dest_dir,'assets/')
    try:
        command = [
            'rsync',
            '-av',
            source_assets_path,  # Ensure the source directory ends with a slash
            destination_assets_path
        ]

        result = subprocess.run(command, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

        print("rsync output:", result.stdout.decode())
        print("rsync of asset folder done")

    except subprocess.CalledProcessError as e:
        print("rsync failed with the following error:")
        print(e.stderr.decode())
        print(f"when trying to copy from {source_assets_path} to {destination_assets_path}")

    print(f"Article '{article.title}' exported.")

cms/templates/cms/about.html
{% load static %} <!DOCTYPE html>

<html data-bs-theme="light" lang="en">
<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1.0, shrink-to-fit=no" name="viewport"/>
<title>About us - Brand</title>
<link href="{% static 'cms/assets/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic&amp;display=swap" rel="stylesheet"/>
<link href="{% static 'cms/assets/fonts/font-awesome.min.css' %}" rel="stylesheet"/>
</head>
<body>
<nav class="navbar navbar-expand-lg fixed-top" id="mainNav">
<div class="container"><a class="navbar-brand" href="{% url 'cms:index' %}">{{site_name}}</a><button aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-bs-target="#navbarResponsive" data-bs-toggle="collapse"><i class="fa fa-bars"></i></button>
<div class="collapse navbar-collapse" id="navbarResponsive">
<ul class="navbar-nav ms-auto">
<li class="nav-item"></li>
<li class="nav-item"><a class="nav-link" href="{% url 'cms:about' %}">About</a></li>
<li class="nav-item"><a class="nav-link" href="{% url 'cms:contact' %}">Contact</a></li>
<li class="nav-item"><a class="nav-link" href="{% url 'cms:index' %}">Blog</a></li>
</ul>
</div>
</div>
</nav>
<header class="masthead" style="background-image:url('{% static 'cms/assets/img/about-bg.jpg' %}');">
<div class="overlay"></div>
<div class="container">
<div class="row">
<div class="col-md-10 col-lg-8 mx-auto position-relative">
<div class="site-heading">
<h1>About Me</h1><span class="subheading">This is what I do</span>
</div>
</div>
</div>
</div>
</header>
<div class="container">
<div class="row">
<div class="col-md-10 col-lg-8 mx-auto">
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
</div>
</div>
</div>
<hr/>
<footer>
<div class="container">
<div class="row">
<div class="col-md-10 col-lg-8 mx-auto">
<p class="text-muted copyright">Copyright © {{site_name}} {% now "Y" %}</p>
</div>
</div>
</div>
</footer>
<script src="{% static 'cms/assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'cms/assets/js/clean-blog.js' %}"></script>
</body>
</html>

cms/templates/cms/article_static.html
<html>
<head>
    <title>{{ article.title }}</title>
</head>
<body>
    <h1>{{ article.title }}</h1>
    <div>{{ article.content|safe }}</div>
    <p>By {{ article.author }}</p>
</body>
</html>

cms/templates/cms/contact.html
{% load static %} <!DOCTYPE html>

<html data-bs-theme="light" lang="en">
<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1.0, shrink-to-fit=no" name="viewport"/>
<title>Contact us - Brand</title>
<link href="{% static 'cms/assets/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic&amp;display=swap" rel="stylesheet"/>
<link href="{% static 'cms/assets/fonts/font-awesome.min.css' %}" rel="stylesheet"/>
</head>
<body>
<nav class="navbar navbar-expand-lg fixed-top" id="mainNav">
<div class="container"><a class="navbar-brand" href="{% url 'cms:index' %}">{{site_name}}</a><button aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-bs-target="#navbarResponsive" data-bs-toggle="collapse"><i class="fa fa-bars"></i></button>
<div class="collapse navbar-collapse" id="navbarResponsive">
<ul class="navbar-nav ms-auto">
<li class="nav-item"></li>
<li class="nav-item"><a class="nav-link" href="{% url 'cms:about' %}">About</a></li>
<li class="nav-item"><a class="nav-link" href="{% url 'cms:contact' %}">Contact</a></li>
<li class="nav-item"><a class="nav-link" href="{% url 'cms:index' %}">Blog</a></li>
</ul>
</div>
</div>
</nav>
<header class="masthead" style="background-image:url('{% static 'cms/assets/img/contact-bg.jpg' %}');">
<div class="overlay"></div>
<div class="container">
<div class="row">
<div class="col-md-10 col-lg-8 mx-auto position-relative">
<div class="site-heading">
<h1>Contact Me</h1><span class="subheading">Have questions? I have answers.</span>
</div>
</div>
</div>
</div>
</header>
<div class="container">
<div class="row">
<div class="col-md-10 col-lg-8 mx-auto">
<p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
<form id="contactForm" name="sentMessage">
<div>
<div class="form-floating mb-3"><input class="form-control" id="name" placeholder="Name" required="" type="text"/><label class="form-label" for="name">Name</label><small class="form-text text-danger help-block"></small></div>
</div>
<div>
<div class="form-floating mb-3"><input class="form-control" id="email" placeholder="Email Address" required="" type="email"/><label class="form-label">Email Address</label><small class="form-text text-danger help-block"></small></div>
</div>
<div>
<div class="form-floating mb-3"><input class="form-control" id="phone" placeholder="Phone Number" required="" type="tel"/><label class="form-label">Phone Number</label><small class="form-text text-danger help-block"></small></div>
</div>
<div>
<div class="form-floating mb-3"><textarea class="form-control" data-validation-required-message="Please enter a message." id="message" placeholder="Message" required="" style="height: 150px;"></textarea><label class="form-label">Message</label><small class="form-text text-danger help-block"></small></div>
</div>
<div id="success"></div>
<div class="mb-3"><button class="btn btn-primary" id="sendMessageButton" type="submit">Send</button></div>
</form>
</div>
</div>
</div>
<hr/>
<footer>
<div class="container">
<div class="row">
<div class="col-md-10 col-lg-8 mx-auto">
<p class="text-muted copyright">Copyright © {{site_name}} {% now "Y" %}</p>
</div>
</div>
</div>
</footer>
<script src="{% static 'cms/assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'cms/assets/js/clean-blog.js' %}"></script>
</body>
</html>

cms/templates/cms/index.html
{% load static %} <!DOCTYPE html>

<html data-bs-theme="light" lang="en">
<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1.0, shrink-to-fit=no" name="viewport"/>
<title>Blog Post - Brand</title>
<link href="{% static 'cms/assets/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic&amp;display=swap" rel="stylesheet"/>
<link href="{% static 'cms/assets/fonts/font-awesome.min.css' %}" rel="stylesheet"/>
</head>
<body>
<nav class="navbar navbar-expand-lg fixed-top" id="mainNav">
<div class="container"><a class="navbar-brand" href="{% url 'cms:index' %}">{{site_name}}</a><button aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-bs-target="#navbarResponsive" data-bs-toggle="collapse"><i class="fa fa-bars"></i></button>
<div class="collapse navbar-collapse" id="navbarResponsive">
<ul class="navbar-nav ms-auto">
<li class="nav-item"></li>
<li class="nav-item"><a class="nav-link" href="{% url 'cms:about' %}">About</a></li>
<li class="nav-item"><a class="nav-link" href="{% url 'cms:contact' %}">Contact</a></li>
<li class="nav-item"><a class="nav-link" href="{% url 'cms:index' %}">Blog</a></li>
</ul>
</div>
</div>
</nav>
<header class="masthead" style="background-image: url('{% static 'cms/assets/img/post-bg.jpg' %}');height: 500px;">
<div class="overlay"></div>
<div class="container">
<div class="row">
<div class="col-md-10 col-lg-8 mx-auto position-relative">
<div class="post-heading">
<h1>{{ site_headline }}</h1>
<h2 class="subheading">{{site_teaser}}</h2>
</div>
</div>
</div>
</div>
</header>
<div class="container">
<div class="row">
<div class="col-md-10 col-lg-8">
{% for article in articles %}<div>
<div class="post-preview"><a href="articles/{{article.slug}}">
<h2 class="post-title">{{ article.title }}</h2>
<h3 class="post-subtitle">{{article.teaser}}</h3>
</a></div>
<hr/>
</div>{% endfor %}
</div>
</div>
</div>
<footer>
<div class="container">
<div class="row">
<div class="col-md-10 col-lg-8 mx-auto">
<p class="text-muted copyright">Copyright © {{site_name}} {% now "Y" %}</p>
</div>
</div>
</div>
</footer>
<script src="{% static 'cms/assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'cms/assets/js/clean-blog.js' %}"></script>
</body>
</html>

cms/templates/cms/post.html
{% load static %} <!DOCTYPE html>

<html data-bs-theme="light" lang="en">
<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1.0, shrink-to-fit=no" name="viewport"/>
<title>Blog Post - Brand</title>
<link href="{% static 'cms/assets/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&amp;display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic&amp;display=swap" rel="stylesheet"/>
<link href="{% static 'cms/assets/fonts/font-awesome.min.css' %}" rel="stylesheet"/>
</head>
<body>
<nav class="navbar navbar-expand-lg fixed-top" id="mainNav">
<div class="container"><a class="navbar-brand" href="{% url 'cms:index' %}">{{site_name}}</a><button aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-bs-target="#navbarResponsive" data-bs-toggle="collapse"><i class="fa fa-bars"></i></button>
<div class="collapse navbar-collapse" id="navbarResponsive">
<ul class="navbar-nav ms-auto">
<li class="nav-item"></li>
<li class="nav-item"><a class="nav-link" href="{% url 'cms:about' %}">About</a></li>
<li class="nav-item"><a class="nav-link" href="{% url 'cms:contact' %}">Contact</a></li>
<li class="nav-item"><a class="nav-link" href="{% url 'cms:index' %}">Blog</a></li>
</ul>
</div>
</div>
</nav>
<header class="masthead" style="background-image: url('{% static 'cms/assets/img/post-bg.jpg' %}');height: 500px;">
<div class="overlay"></div>
<div class="container">
<div class="row">
<div class="col-md-10 col-lg-8 mx-auto position-relative">
<div class="post-heading">
<h1>{{ article.title }}</h1>
<h2 class="subheading">{{article.teaser}}</h2>
</div>
</div>
</div>
</div>
</header>
<article>
<div class="container">
<div class="row">
<div class="col-md-10 col-lg-8 mx-auto">
<div>{{article.content.html|safe}}</div>
</div>
</div>
</div>
</article>
<footer>
<div class="container">
<div class="row">
<div class="col-md-10 col-lg-8 mx-auto">
<p class="text-muted copyright">Copyright © {{site_name}} {% now "Y" %}</p>
</div>
</div>
</div>
</footer>
<script src="{% static 'cms/assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'cms/assets/js/clean-blog.js' %}"></script>
</body>
</html>

cms/templates/widgets/quill_editor.html
<div>
    <div id="editor-container" style="min-height: 300px;"></div>

    <!-- Hidden textarea for form submission -->
    {{ widget }}

    <script>
        var quill = new Quill('#editor-container', {
            theme: 'snow',
        });

        // Set the initial content if editing an existing article
        quill.setContents(quill.clipboard.convert('{{ widget.value|escapejs }}'))

        // On form submission, update the hidden textarea with Quill.js content
        document.querySelector('form').addEventListener('submit', function() {
            document.querySelector('#{{ widget.attrs.id }}').value = quill.root.innerHTML;
        });
    </script>
</div>